var GAME_LEVELS = [
  ["         v                v                   v         ",
   "                v                                       ",
   "           v                    v                       ",
   "                         v                    v         ",
   "                                                        ",
   "                                                        ",
   "  xxxxxxxxxxx                                        x  ",
   "  x         x                                        x  ",
   "  x      c  x                                        x  ",
   "  x       xxx                                        x  ",
   "  x                                                  x  ",
   "  x                                                  x  ",
   "  x c                                                x  ",
   "  xxx                                                x  ",
   "  x                                                  x  ",
   "  x                                                  x  ",
   "  x  @                                            o  x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                          ",
   "             v                                                                                            ",
   "                                              v            v                  v               v           ",
   "                                                                                                          ",
   "                                   v                                                                      ",
   "                                                                                              v           ",
   "                          v                                                 v                             ",
   "                                                   v                                                      ",
   "                                                                                                          ",
   "        v                                                                                          v      ",
   "                                                                                      v                   ",
   "                                                                                                          ",
   "                                xxxxxxxxxxxxxxxxxx                                                        ",
   "           c         xxxx                                                                                 ",
   "         xxxxx               xxx               xxxx     xxxxxx                                            ",
   "                                      xxxx                                                                ",
   "    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                    x",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                  x",
   "                                                                    x  xx                                x",
   "                                                               xxx  x    xx                              x",
   "      @                                               xxx           x      xx                            x",
   "      xx                                                            x        xx                          x",
   "      xx                                                     xxx    x          xx                        x",
   "     xxx                  xxxxxxxxxx                                x            xx                      x",
   "      xx                 xxxxx                                   xxxx              xx                    x",
   "      xx                xxxxxx                                 xxxx                                      x",
   "  xxxxxxxxx    xx     xxxxxxx         c          c    c    xxxx                                          x",
   "xxxxxxxxxxxxx!!!!!!!!xxxxxxxxyyyyyyyyyxxxxxxxxxxxxxxxxxxxxxxxx                         ss  o   ss        x",
   "xxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxxxxxxxxxxyyyyyyyyx",
   "xxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["     v            v          v                       v           v      v           v                         ",
   "       v      v          v        v                x        v      v            v                             ",
   "                  v              x                                       v x            v           v         ",
   "  x         v  x         v    xx          x  x    x      v        xxx         x x x                           ",
   "  x                                       x                xxx xxx         x                    x             ",
   "  x x              xxx             x          x           x        xxx         x         xxx               x  ",
   "  x      @       x xxxx   x   xx                    x        x             xxx                 x        x     ",
   "  x      x         xxx        x    xxx    x                             x x        xxx          xx            ",
   "  x     x           xxx    x  xxxxxxx    xx         xx xxx        xx          x                               ",
   "  x              x  xxxxx     xyyyyyyyyyyyx                                                                o  ",
   "  xyyyy!!!!!!!!!!!!!!!!!!!!!!!!yyyyyyyyyyy!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!yyyyyyxxxxxxxxx  ",
   "  xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxxxxxxxxx  ",
   "  xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
